test: ../../src/lib/Plansza.cpp ../../src/lib/Algorithm.cpp ../../src/lib/funkcje.cpp BoardTest.cpp AlgorithmTest.cpp main_test.cpp
	g++ -Wall -g -pthread ../../src/lib/Plansza.cpp ../../src/lib/Algorithm.cpp ../../src/lib/funkcje.cpp BoardTest.cpp AlgorithmTest.cpp main_test.cpp  -lgtest_main  -lgtest -lpthread -o test
